[colors]

[colors.primary]
background = '#111c18'
foreground = '#C1C497'

[colors.normal]
black   = "#23372B"  # Inactive_fg
red     = "#FF5345"  # Temp_end, for red accents
green   = "#549e6a"  # Upload_end, for executables
yellow  = "#459451"  # Temp_mid
blue    = "#97CB98"  # Box outline, lighter teal for directories
magenta = "#D2689C"  # Download_mid
cyan    = "#2DD5B7"  # Cpu_end, for symlinks
white   = "#F6F5DD"  # Graph_text

[colors.bright]
black   = "#53685B"  # arrows, file size
red     = "#db9f9c"  # Process_end
green   = "#72cfa3"  # Process_start, brighter green
yellow  = "#D8C14C"  # Process_mid
blue    = "#ACD4CF"  # Temp_start, brighter for bold dirs
magenta = "#75bbb3"  # Download_start
cyan    = "#8CD3CB"  # Upload_mid
white   = "#9eebb3"  # Title

[colors.cursor]
text   = "#000000"
cursor = "#D7C995"
